In [1]:
import gym
import numpy as np

In [3]:
env = gym.make('FrozenLake-v1')

In [4]:
Q = np.zeros([env.observation_space.n,env.action_space.n])
lr = .8
y = .95
num_episodes = 2000
rList = []
for i in range(num_episodes):
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    while j < 99:
        j+=1
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        s1,r,d,_ = env.step(a)
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    rList.append(rAll)

In [5]:
print ("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.527


In [6]:
print ("Final Q-Table Values")
print (Q)

Final Q-Table Values
[[3.03640634e-01 7.63533377e-03 8.87031927e-03 4.38926425e-03]
 [6.37646985e-04 2.94383033e-03 7.58184636e-04 3.04197862e-01]
 [1.69422128e-01 1.11101738e-02 3.76910366e-03 9.88165858e-03]
 [7.21822298e-04 1.57844335e-04 6.12207407e-04 1.20539052e-02]
 [2.84161401e-01 2.07201697e-03 9.66701943e-03 1.01656308e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [9.18463674e-04 3.73441519e-06 3.39510060e-02 1.30685283e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.34573369e-03 4.37135469e-03 1.32616537e-03 2.22545262e-01]
 [3.60922552e-04 2.03405216e-01 1.55708025e-03 3.86254454e-04]
 [8.10359629e-02 2.97660472e-05 1.05520156e-03 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.37638153e-03 1.30846841e-04 1.71104034e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 8.16143791e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.